"""
Disposable Email Domain Detector

Detects temporary/disposable email services commonly used for abuse,
spam, and avoiding accountability. Maintains a curated set of known
disposable domains plus the ability to load external lists.
"""

import logging
import os
from typing import Set

logger = logging.getLogger(__name__)

# Curated list of the most common disposable email domains
# Sources: aggregated from multiple public blocklists
DISPOSABLE_DOMAINS: Set[str] = {
    # Major disposable services
    "10minutemail.com", "10minutemail.net", "10minutemail.org",
    "20minutemail.com", "20minutemail.it",
    "33mail.com",
    "adf.ly",
    "amilegit.com",
    "anonbox.net",
    "anonymbox.com",
    "antichef.com",
    "binkmail.com",
    "bio-muesli.net",
    "bobmail.info",
    "bodhi.lawlita.com",
    "bofthew.com",
    "brefmail.com",
    "broadbandninja.com",
    "bsnow.net",
    "bugmenot.com",
    "bumpymail.com",
    "casualdx.com",
    "centermail.com", "centermail.net",
    "chogmail.com",
    "choicemail1.com",
    "clixser.com",
    "clrmail.com",
    "cmail.net", "cmail.org",
    "coldemail.info",
    "cool.fr.nf",
    "correo.blogos.net",
    "cosmorph.com",
    "courriel.fr.nf",
    "courrieltemporaire.com",
    "crapmail.org",
    "crazymailing.com",
    "cubiclink.com",
    "curryworld.de",
    "cust.in",
    "cuvox.de",
    "dacoolest.com",
    "dandikmail.com",
    "dayrep.com",
    "dcemail.com",
    "deadaddress.com",
    "deadchildren.org",
    "deadfake.cf", "deadfake.ga", "deadfake.ml", "deadfake.tk",
    "dealja.com",
    "despam.it", "despammed.com",
    "devnullmail.com",
    "dfgh.net",
    "digitalsanctuary.com",
    "dingbone.com",
    "discard.cf", "discard.email", "discard.ga", "discard.gq", "discard.ml", "discard.tk",
    "discardmail.com", "discardmail.de",
    "dispomail.eu",
    "disposable.cf", "disposable.ga", "disposable.ml",
    "disposableaddress.com",
    "disposableemailaddresses.emailmiser.com",
    "disposableinbox.com",
    "dispose.it",
    "dispostable.com",
    "dm.w3internet.co.uk",
    "dodgeit.com", "dodgit.com", "dodgit.org",
    "dontreg.com", "dontsendmespam.de",
    "drdrb.com", "drdrb.net",
    "dropmail.me",
    "duam.net",
    "dudmail.com",
    "dump-email.info",
    "dumpandjunk.com",
    "dumpmail.de",
    "dumpyemail.com",
    "e4ward.com",
    "easytrashmail.com",
    "einrot.com",
    "email60.com",
    "emaildienst.de",
    "emailgo.de",
    "emailias.com",
    "emailigo.de",
    "emailinfive.com",
    "emaillime.com",
    "emailmiser.com",
    "emailproxsy.com",
    "emails.ga",
    "emailsensei.com",
    "emailtemporario.com.br",
    "emailto.de",
    "emailwarden.com",
    "emailx.at.hm",
    "emailxfer.com",
    "emz.net",
    "enterto.com",
    "ephemail.net",
    "etranquil.com", "etranquil.net", "etranquil.org",
    "evopo.com",
    "explodemail.com",
    "express.net.ua",
    "eyepaste.com",
    "fakeinbox.com",
    "fakeinformation.com",
    "fakemail.fr",
    "fakemailz.com",
    "fammix.com",
    "fansworldwide.de",
    "fastacura.com",
    "fastchevy.com",
    "fastchrysler.com",
    "fastkawasaki.com",
    "fastmazda.com",
    "fastmitsubishi.com",
    "fastnissan.com",
    "fastsubaru.com",
    "fastsuzuki.com",
    "fasttoyota.com",
    "fastyamaha.com",
    "filzmail.com",
    "fixmail.tk",
    "fizmail.com",
    "fleckens.hu",
    "fr33mail.info",
    "frapmail.com",
    "freemail.ms",
    "freemails.cf", "freemails.ga", "freemails.ml",
    "freundin.ru",
    "friendlymail.co.uk",
    "front14.org",
    "fuckingduh.com",
    "fudgerub.com",
    "funktioniert.net",
    "garliclife.com",
    "get1mail.com", "get2mail.fr",
    "getairmail.cf", "getairmail.com", "getairmail.ga", "getairmail.gq", "getairmail.ml", "getairmail.tk",
    "getmails.eu",
    "getonemail.com", "getonemail.net",
    "ghosttexter.de",
    "giantmail.de",
    "girlsundertheinfluence.com",
    "gishpuppy.com",
    "goemailgo.com",
    "gorillaswithdirtyarmpits.com",
    "gotmail.com", "gotmail.net", "gotmail.org",
    "gotti.otherinbox.com",
    "great-host.in",
    "greensloth.com",
    "grr.la",
    "gsrv.co.uk",
    "guerillamail.biz", "guerillamail.com", "guerillamail.de", "guerillamail.info",
    "guerillamail.net", "guerillamail.org",
    "guerrillamail.biz", "guerrillamail.com", "guerrillamail.de", "guerrillamail.info",
    "guerrillamail.net", "guerrillamail.org",
    "guerrillamailblock.com",
    "gustr.com",
    "h8s.org",
    "haltospam.com",
    "harakirimail.com",
    "hartbot.de",
    "hatespam.org",
    "herp.in",
    "hidemail.de",
    "hidzz.com",
    "hmamail.com",
    "hopemail.biz",
    "hotpop.com",
    "hulapla.de",
    "ichimail.com",
    "imails.info",
    "inbax.tk",
    "inbox.si",
    "inboxalias.com",
    "inboxclean.com", "inboxclean.org",
    "inboxed.im", "inboxed.pw",
    "incognitomail.com", "incognitomail.net", "incognitomail.org",
    "insorg-mail.info",
    "ipoo.org",
    "irish2me.com",
    "iwi.net",
    "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org",
    "jnxjn.com",
    "jourrapide.com",
    "junk1e.com",
    "junkmail.com", "junkmail.ga", "junkmail.gq",
    "kasmail.com",
    "kaspop.com",
    "keepmymail.com",
    "killmail.com", "killmail.net",
    "kimsdisk.com",
    "kingsq.ga",
    "kir.ch.tc",
    "klassmaster.com", "klassmaster.net",
    "klzlk.com",
    "koszmail.pl",
    "kurzepost.de",
    "lawlita.com",
    "letthemeatspam.com",
    "lhsdv.com",
    "lifebyfood.com",
    "link2mail.net",
    "litedrop.com",
    "lol.ovpn.to",
    "lookugly.com",
    "lopl.co.cc",
    "lortemail.dk",
    "lovemeleaveme.com",
    "lr7.us", "lr78.com",
    "lroid.com",
    "lukop.dk",
    "m21.cc",
    "mail-hierarchie.de", "mail-temporaire.fr",
    "mail.by", "mail.mezimages.net", "mail.zp.ua",
    "mail114.net",
    "mail2rss.org",
    "mail333.com",
    "mail4trash.com",
    "mailbidon.com",
    "mailblocks.com",
    "mailbucket.org",
    "mailcat.biz",
    "mailcatch.com",
    "mailde.de", "mailde.info",
    "maildrop.cc", "maildrop.cf", "maildrop.ga", "maildrop.gq", "maildrop.ml",
    "maildu.de",
    "maileater.com",
    "mailed.ro",
    "mailexpire.com",
    "mailfa.tk",
    "mailforspam.com",
    "mailfree.ga", "mailfree.gq", "mailfree.ml",
    "mailfreeonline.com",
    "mailfs.com",
    "mailguard.me",
    "mailhazard.com", "mailhazard.us",
    "mailhz.me",
    "mailimate.com",
    "mailin8r.com",
    "mailinater.com",
    "mailinator.com", "mailinator.net", "mailinator.org",
    "mailinator2.com",
    "mailincubator.com",
    "mailismagic.com",
    "mailjunk.cf", "mailjunk.ga", "mailjunk.gq", "mailjunk.ml", "mailjunk.tk",
    "mailmate.com",
    "mailme.ir", "mailme.lv",
    "mailmetrash.com",
    "mailmoat.com",
    "mailms.com",
    "mailnator.com",
    "mailnesia.com",
    "mailnull.com",
    "mailorg.org",
    "mailpick.biz",
    "mailquack.com",
    "mailrock.biz",
    "mailscrap.com",
    "mailshell.com",
    "mailsiphon.com",
    "mailslite.com",
    "mailtemp.info",
    "mailtothis.com",
    "mailtrash.net",
    "mailtv.net", "mailtv.tv",
    "mailzilla.com", "mailzilla.org",
    "makemetheking.com",
    "manifestgenerator.com",
    "manybrain.com",
    "mbx.cc",
    "mega.zik.dj",
    "meinspamschutz.de",
    "meltmail.com",
    "messagebeamer.de",
    "mezimages.net",
    "mfsa.ru", "mfsa.info",
    "mierdamail.com",
    "ministry-of-silly-walks.de",
    "mintemail.com",
    "misterpinball.de",
    "mmmmail.com",
    "moakt.com", "moakt.co", "moakt.ws",
    "mobileninja.co.uk",
    "mohmal.com", "mohmal.im", "mohmal.in", "mohmal.tech",
    "moncourrier.fr.nf",
    "monemail.fr.nf",
    "monmail.fr.nf",
    "monumentmail.com",
    "ms9.mailslite.com",
    "msa.minsmail.com",
    "mt2009.com", "mt2014.com", "mt2015.com",
    "mtmdev.com",
    "muimail.com",
    "mundomail.net",
    "myalias.pw",
    "mymail-in.net",
    "mymailoasis.com",
    "mynetstore.de",
    "mypacks.net",
    "mypartyclip.de",
    "myphantom.com",
    "mysamp.de",
    "mytemp.email",
    "mytempemail.com",
    "mytempmail.com",
    "mytrashmail.com",
    "nabala.com",
    "neomailbox.com",
    "nepwk.com",
    "nervmich.net", "nervtansen.de",
    "netmails.com", "netmails.net",
    "neverbox.com",
    "no-spam.ws",
    "noblepioneer.com",
    "nobulk.com",
    "noclickemail.com",
    "nogmailspam.info",
    "nomail.xl.cx", "nomail2me.com",
    "nomorespamemails.com",
    "nonspam.eu", "nonspammer.de",
    "noref.in",
    "nospam.ze.tc", "nospam4.us",
    "nospamfor.us", "nospammail.net", "nospamthanks.info",
    "nothingtoseehere.ca",
    "nowmymail.com",
    "nurfuerspam.de",
    "nwldx.com",
    "objectmail.com",
    "obobbo.com",
    "odaymail.com",
    "one-time.email",
    "oneoffemail.com",
    "oneoffmail.com",
    "onewaymail.com",
    "oopi.org",
    "ordinaryamerican.net",
    "otherinbox.com",
    "ourklips.com",
    "outlawspam.com",
    "ovpn.to",
    "owlpic.com",
    "pancakemail.com",
    "pimpedupmyspace.com",
    "pjjkp.com",
    "plexolan.de",
    "politikerclub.de",
    "poofy.org",
    "pookmail.com",
    "privacy.net",
    "privy-mail.com", "privymail.de",
    "proxymail.eu",
    "prtnx.com",
    "punkass.com",
    "putthisinyourspa.com",
    "pwrby.com",
    # "qq.com",  # REMOVED — QQ Mail is one of China's largest legitimate providers (hundreds of millions of users)
    "quickinbox.com",
    "rcpt.at",
    "reallymymail.com",
    "recode.me",
    "recursor.net",
    "recyclemail.dk",
    "regbypass.com", "safe-mail.net",
    "rejectmail.com",
    "reliable-mail.com",
    "remail.cf", "remail.ga",
    "rhyta.com",
    "rklips.com",
    "rmqkr.net",
    "royal.net",
    "rppkn.com",
    "rtrtr.com",
    "s0ny.net",
    "safersignup.de",
    "safetymail.info", "safetypost.de",
    "sandelf.de",
    "saynotospams.com",
    "scatmail.com",
    "schafmail.de",
    "schrott-email.de",
    "secretemail.de",
    "secure-mail.biz", "secure-mail.cc",
    "selfdestructingmail.com",
    "sendspamhere.com",
    "shieldedmail.com",
    "shiftmail.com",
    "shitmail.me", "shitmail.org",
    "shortmail.net",
    "sibmail.com",
    "sinnlos-mail.de",
    "siteposter.net",
    "skeefmail.com",
    "slaskpost.se",
    "slipry.net",
    "slopsbox.com",
    "slowslow.de",
    "smashmail.de",
    "smellfear.com",
    "snakemail.com",
    "sneakemail.com",
    "sneakymail.de",
    "snkmail.com",
    "sofimail.com",
    "sofort-mail.de",
    "softpls.asia",
    "sogetthis.com",
    "soodonims.com",
    "spam4.me",
    "spamavert.com",
    "spambob.com", "spambob.net", "spambob.org",
    "spambog.com", "spambog.de", "spambog.ru",
    "spambox.us",
    "spamcannon.com", "spamcannon.net",
    "spamcero.com",
    "spamcorptastic.com",
    "spamcowboy.com", "spamcowboy.net", "spamcowboy.org",
    "spamday.com",
    "spamex.com",
    "spamfighter.cf", "spamfighter.ga", "spamfighter.gq", "spamfighter.ml", "spamfighter.tk",
    "spamfree24.com", "spamfree24.de", "spamfree24.eu", "spamfree24.info",
    "spamfree24.net", "spamfree24.org",
    "spamgoes.in",
    "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
    "spamherelots.com", "spamhereplease.com",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com", "spaml.de",
    "spammotel.com",
    "spamobox.com",
    "spamoff.de",
    "spamslicer.com",
    "spamspot.com",
    "spamstack.net",
    "spamthis.co.uk",
    "spamthisplease.com",
    "spamtrail.com",
    "spamtrap.ro",
    "speed.1s.fr",
    "spoofmail.de",
    "squizzy.de",
    "sry.li",
    "stuffmail.de",
    "supergreatmail.com", "supermailer.jp",
    "superrito.com",
    "superstachel.de",
    "suremail.info",
    "svk.jp",
    "sweetxxx.de",
    "tafmail.com",
    "tagyoureit.com",
    "talkinator.com",
    "tapchicuoihoi.com",
    "teewars.org",
    "teleworm.com", "teleworm.us",
    "temp-mail.org", "temp-mail.ru",
    "tempalias.com",
    "tempe4mail.com",
    "tempemail.biz", "tempemail.co.za", "tempemail.com", "tempemail.net",
    "tempinbox.com", "tempinbox.co.uk",
    "tempmail.eu", "tempmail.it", "tempmail2.com",
    "tempmaildemo.com",
    "tempmailer.com", "tempmailer.de",
    "tempomail.fr",
    "temporarioemail.com.br",
    "temporaryemail.net", "temporaryemail.us",
    "temporaryforwarding.com",
    "temporaryinbox.com",
    "temporarymailaddress.com",
    "tempthe.net",
    "thanksnospam.info",
    "thankyou2010.com",
    "thc.st",
    "thelimestones.com",
    "thisisnotmyrealemail.com",
    "thismail.net", "thismail.ru",
    "throwam.com",
    "throwawayemailaddress.com",
    "tittbit.in",
    "tizi.com",
    "tmailinator.com",
    "toiea.com",
    "toomail.biz",
    "topranklist.de",
    "tradermail.info",
    "trash-amil.com", "trash-mail.at", "trash-mail.cf", "trash-mail.com",
    "trash-mail.de", "trash-mail.ga", "trash-mail.gq", "trash-mail.ml", "trash-mail.tk",
    "trash2009.com", "trash2010.com", "trash2011.com",
    "trashdevil.com", "trashdevil.de",
    "trashemail.de",
    "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.me",
    "trashmail.net", "trashmail.org", "trashmail.ws",
    "trashmailer.com",
    "trashymail.com", "trashymail.net",
    "trialmail.de",
    "trickmail.net",
    "trillianpro.com",
    "turual.com",
    "twinmail.de",
    "tyldd.com",
    "uggsrock.com",
    "umail.net",
    "uniqueme.com",
    "upliftnow.com",
    "uplipht.com",
    "venompen.com",
    "veryreallyme.com",
    "viditag.com",
    "viewcastmedia.com", "viewcastmedia.net", "viewcastmedia.org",
    "vomoto.com",
    "vpn.st",
    "vsimcard.com",
    "vubby.com",
    "wasteland.rfc822.org",
    "watchfull.net",
    "webemail.me",
    "webm4il.info",
    "wegwerfadresse.de",
    "wegwerfemail.com", "wegwerfemail.de",
    "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org",
    "wh4f.org",
    "whatiaas.com",
    "whatpaas.com",
    "whyspam.me",
    "wikidocuslice.com",
    "willhackforfood.biz",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "wuzup.net", "wuzupmail.net",
    "wwwnew.eu",
    "xagloo.com",
    "xemaps.com",
    "xents.com",
    "xjoi.com",
    "xmaily.com",
    "xoxy.net",
    "yapped.net",
    # yeah.net removed: legitimate NetEase (163.com family) Chinese email provider
    "yep.it",
    "yogamaven.com",
    "yomail.info",
    "yopmail.com", "yopmail.fr", "yopmail.gq", "yopmail.net",
    # yourdomain.com removed: generic placeholder, not an actual disposable service
    "ypmail.webarnak.fr.eu.org",
    "yuurok.com",
    "zehnminutenmail.de",
    "zippymail.info",
    "zoaxe.com",
    "zoemail.org",
    "zomg.info",
    "zxcv.com", "zxcvbnm.com",
    "zzz.com",

    # High-volume disposable services (2024-2026)
    "tempr.email", "temp-mail.io",
    "emailondeck.com", "emailfake.com",
    "tmail.ws", "yepmail.com",
    "burnermail.io", "inboxkitten.com",
    "mailsac.com", "throwaway.email",
    "getnada.com", "emailnator.com",

    # NOTE: mail.ru, bk.ru, list.ru, inbox.ru are legitimate Russian email providers — NOT disposable
    # NOTE: internxt.com is a legitimate privacy-focused cloud storage/email provider — NOT disposable
}

# Additional high-risk free TLDs often used for disposable/abuse emails
HIGH_RISK_TLDS = {
    '.tk', '.ml', '.ga', '.cf', '.gq',  # Freenom free TLDs
    '.xyz', '.top', '.wang', '.click', '.link',
    '.work', '.date', '.racing', '.win', '.bid',
    '.stream', '.gdn', '.icu', '.buzz', '.cyou',
}


class DisposableEmailDetector:
    """Detects disposable/temporary email domains."""

    def __init__(self, extra_domains_file: str = None):
        self.domains = set(DISPOSABLE_DOMAINS)
        self.high_risk_tlds = set(HIGH_RISK_TLDS)

        # Load additional domains from file if provided
        if extra_domains_file and os.path.exists(extra_domains_file):
            self._load_extra_domains(extra_domains_file)

        # Also check for a bundled list next to this file
        bundled_path = os.path.join(os.path.dirname(__file__), 'disposable_domains.txt')
        if os.path.exists(bundled_path):
            self._load_extra_domains(bundled_path)

        logger.info(f"DisposableEmailDetector initialized with {len(self.domains)} domains")

    def _load_extra_domains(self, filepath: str):
        """Load additional disposable domains from a text file (one domain per line)."""
        try:
            with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                for line in f:
                    domain = line.strip().lower()
                    if domain and not domain.startswith('#'):
                        self.domains.add(domain)
            logger.info(f"Loaded extra disposable domains from {filepath}")
        except Exception as e:
            logger.warning(f"Failed to load extra domains from {filepath}: {e}")

    def is_disposable(self, domain: str) -> bool:
        """Check if a domain is a known disposable email service."""
        domain = domain.lower().strip()
        return domain in self.domains

    def has_high_risk_tld(self, domain: str) -> bool:
        """Check if the domain uses a high-risk free TLD."""
        domain = domain.lower().strip()
        for tld in self.high_risk_tlds:
            if domain.endswith(tld):
                return True
        return False

    def get_risk_score(self, domain: str) -> float:
        """Return a disposable risk score 0.0 (safe) to 1.0 (definitely disposable)."""
        domain = domain.lower().strip()

        if self.is_disposable(domain):
            return 1.0

        if self.has_high_risk_tld(domain):
            return 0.5

        # Check if the domain name itself contains suspicious patterns
        suspicious_patterns = [
            'temp', 'trash', 'junk', 'spam', 'fake', 'throw',
            'disposable', 'burner', 'guerrilla', 'mailinator',
            'nospam', 'nomail', 'devnull', 'dump', 'discard',
            'anonymous', 'anon',
            'wegwerf',  # German for "throwaway"
        ]
        # Check all labels (not just first) — catches mail.tempbox.net etc.
        domain_without_tld = domain.rsplit('.', 1)[0] if '.' in domain else domain
        for pattern in suspicious_patterns:
            if pattern in domain_without_tld:
                return 0.7

        return 0.0

    @property
    def domain_count(self) -> int:
        """Return the number of known disposable domains."""
        return len(self.domains)
